apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    uid: questdb
    access: proxy
    url: localhost:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      postgresVersion: 1200
      timescaledb: false
      sslmode: disable
    isDefault: true
    editable: true
