"""HTML report builder for backtest results."""

from __future__ import annotations

from typing import Any

import pandas as pd
import plotly.graph_objects as go

from src.reports.utils import (
    extract_equity,
    extract_monthly_returns,
    extract_trades,
    fmt_float,
    fmt_pct,
    is_positive,
)


def build_html(
    results: dict[str, Any],
    strategy_name: str,
    symbol: str,
    generated_at: str,
) -> str:
    """Assemble the full standalone HTML report string."""
    stats_html = render_stats_table(results)
    equity_html = build_equity_chart_html(results)
    monthly_html = build_monthly_returns_html(results)
    trades_html = render_trade_table(results, symbol)
    drawdown_html = build_drawdown_chart_html(results)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Backtest Report - {strategy_name} | {symbol}</title>
<style>
  :root {{ --bg: #0f1117; --card: #1a1d2e; --text: #e2e8f0; --muted: #94a3b8; --accent: #6366f1; --green: #22c55e; --red: #ef4444; }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.6; }}
  h1 {{ font-size: 1.8rem; margin-bottom: .25rem; }}
  h2 {{ font-size: 1.3rem; margin: 2rem 0 1rem; color: var(--accent); }}
  .subtitle {{ color: var(--muted); font-size: .95rem; margin-bottom: 2rem; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat-card {{ background: var(--card); border-radius: 12px; padding: 1.2rem; text-align: center; }}
  .stat-card .label {{ color: var(--muted); font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; }}
  .stat-card .value {{ font-size: 1.6rem; font-weight: 700; margin-top: .3rem; }}
  .value.positive {{ color: var(--green); }}
  .value.negative {{ color: var(--red); }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ padding: .6rem .8rem; text-align: left; border-bottom: 1px solid #2d3148; font-size: .9rem; }}
  th {{ color: var(--muted); font-weight: 600; }}
  .chart-container {{ background: var(--card); border-radius: 12px; padding: 1rem; margin: 1rem 0; }}
  .trade-buy {{ color: var(--green); }}
  .trade-sell {{ color: var(--red); }}
  footer {{ margin-top: 3rem; color: var(--muted); font-size: .8rem; text-align: center; }}
</style>
</head>
<body>
<h1>Backtest Report</h1>
<p class="subtitle">{strategy_name} - {symbol} - Generated {generated_at}</p>

<h2>Summary Statistics</h2>
{stats_html}

<h2>Equity Curve</h2>
<div class="chart-container">{equity_html}</div>

<h2>Monthly Returns Heatmap</h2>
<div class="chart-container">{monthly_html}</div>

<h2>Drawdown</h2>
<div class="chart-container">{drawdown_html}</div>

<h2>Trade Log</h2>
{trades_html}

<footer>Generated by AI Trading Architecture - BacktestReport</footer>
</body>
</html>"""


def render_stats_table(results: dict[str, Any]) -> str:
    items = [
        ("Total Return", fmt_pct(results.get("total_return")), is_positive(results.get("total_return", 0))),
        ("Sharpe Ratio", fmt_float(results.get("sharpe_ratio"), 2), is_positive(results.get("sharpe_ratio", 0))),
        ("Max Drawdown", fmt_pct(results.get("max_drawdown")), False),
        ("Win Rate", fmt_pct(results.get("win_rate")), is_positive(results.get("win_rate", 0) - 50)),
        ("Profit Factor", fmt_float(results.get("profit_factor"), 2), is_positive(results.get("profit_factor", 1) - 1)),
        ("Total Trades", str(results.get("total_trades", "-")), None),
        ("CAGR", fmt_pct(results.get("cagr")), is_positive(results.get("cagr", 0))),
        ("Sortino", fmt_float(results.get("sortino_ratio"), 2), is_positive(results.get("sortino_ratio", 0))),
    ]
    cards = []
    for label, value, positive in items:
        cls = ""
        if positive is True:
            cls = "positive"
        elif positive is False:
            cls = "negative"
        cards.append(
            f'<div class="stat-card">'
            f'<div class="label">{label}</div>'
            f'<div class="value {cls}">{value}</div>'
            f"</div>"
        )
    return f'<div class="stats-grid">{"".join(cards)}</div>'


def build_equity_chart_html(results: dict[str, Any]) -> str:
    equity = extract_equity(results)
    if equity is None or equity.empty:
        return "<p style='color:#94a3b8'>No equity curve data.</p>"

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=equity.index,
            y=equity.values,
            mode="lines",
            name="Equity",
            line=dict(color="#6366f1", width=2),
            fill="tozeroy",
            fillcolor="rgba(99,102,241,0.15)",
        )
    )
    fig.update_layout(
        template="plotly_dark",
        height=400,
        margin=dict(l=50, r=20, t=30, b=40),
        xaxis_title="Date",
        yaxis_title="Portfolio Value ($)",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#e2e8f0"),
    )
    return fig.to_html(include_plotlyjs=True, full_html=False)


def build_monthly_returns_html(results: dict[str, Any]) -> str:
    monthly = extract_monthly_returns(results)
    if monthly is None or monthly.empty:
        return "<p style='color:#94a3b8'>No monthly returns data.</p>"

    fig = go.Figure()
    fig.add_trace(
        go.Heatmap(
            z=monthly.values,
            x=monthly.columns,
            y=monthly.index,
            colorscale="RdYlGn",
            zmid=0,
            text=monthly.map(lambda v: f"{v:+.1f}%" if pd.notna(v) else ""),
            texttemplate="%{text}",
            textfont=dict(size=11, color="white"),
            hovertemplate="Year: %{y}<br>Month: %{x}<br>Return: %{z:.2f}%<extra></extra>",
        )
    )
    fig.update_layout(
        template="plotly_dark",
        height=350,
        margin=dict(l=60, r=20, t=30, b=40),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#e2e8f0"),
    )
    return fig.to_html(include_plotlyjs=True, full_html=False)


def render_trade_table(results: dict[str, Any], symbol: str) -> str:
    trades = extract_trades(results)
    if not trades:
        return "<p style='color:#94a3b8'>No trade data.</p>"

    rows = []
    for trade in trades[:200]:
        side_cls = (
            "trade-buy"
            if str(trade.get("side", "")).lower() in ("buy", "long")
            else "trade-sell"
        )
        pnl = trade.get("pnl", trade.get("profit", 0))
        pnl_cls = "trade-buy" if pnl >= 0 else "trade-sell"
        rows.append(
            f"<tr>"
            f"<td>{trade.get('date', trade.get('datetime', trade.get('time', '')))}</td>"
            f"<td class='{side_cls}'>{trade.get('side', '').upper()}</td>"
            f"<td>{trade.get('symbol', symbol)}</td>"
            f"<td>{fmt_float(trade.get('price', trade.get('fill_price')), 2)}</td>"
            f"<td>{trade.get('quantity', trade.get('size', ''))}</td>"
            f"<td class='{pnl_cls}'>{fmt_float(pnl, 2)}</td>"
            f"</tr>"
        )
    return (
        "<table>"
        "<thead><tr><th>Date</th><th>Side</th><th>Symbol</th><th>Price</th><th>Qty</th><th>PnL</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody>"
        "</table>"
    )


def build_drawdown_chart_html(results: dict[str, Any]) -> str:
    equity = extract_equity(results)
    if equity is None or equity.empty:
        return "<p style='color:#94a3b8'>No data for drawdown.</p>"

    running_max = equity.cummax()
    drawdown = (equity - running_max) / running_max * 100

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=drawdown.index,
            y=drawdown.values,
            mode="lines",
            name="Drawdown %",
            line=dict(color="#ef4444", width=1.5),
            fill="tozeroy",
            fillcolor="rgba(239,68,68,0.2)",
        )
    )
    fig.update_layout(
        template="plotly_dark",
        height=300,
        margin=dict(l=50, r=20, t=30, b=40),
        xaxis_title="Date",
        yaxis_title="Drawdown (%)",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#e2e8f0"),
    )
    return fig.to_html(include_plotlyjs=True, full_html=False)
