"""Markdown report builder for backtest results."""

from __future__ import annotations

from typing import Any

from src.reports.utils import extract_trades, fmt_float, fmt_pct


def build_markdown(
    results: dict[str, Any],
    strategy_name: str,
    symbol: str,
    generated_at: str,
) -> str:
    """Build a Markdown backtest report."""
    lines = [
        "# Backtest Report",
        "",
        f"**Strategy:** {strategy_name}",
        f"**Symbol:** {symbol}",
        f"**Generated:** {generated_at}",
        "",
        "## Summary Statistics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Return | {fmt_pct(results.get('total_return'))} |",
        f"| Sharpe Ratio | {fmt_float(results.get('sharpe_ratio'), 2)} |",
        f"| Max Drawdown | {fmt_pct(results.get('max_drawdown'))} |",
        f"| Win Rate | {fmt_pct(results.get('win_rate'))} |",
        f"| Profit Factor | {fmt_float(results.get('profit_factor'), 2)} |",
        f"| Total Trades | {results.get('total_trades', '-')} |",
        f"| CAGR | {fmt_pct(results.get('cagr'))} |",
        f"| Sortino Ratio | {fmt_float(results.get('sortino_ratio'), 2)} |",
        "",
        "## Equity Curve",
        "",
        "> Run `generate_html()` for embedded charts or open `equity_curve.html`.",
        "",
        "## Trade Log",
        "",
    ]

    trades = extract_trades(results)
    if trades:
        lines.append("| Date | Side | Symbol | Price | Qty | PnL |")
        lines.append("|------|------|--------|-------|-----|-----|")
        for trade in trades[:100]:
            pnl = trade.get("pnl", trade.get("profit", 0))
            lines.append(
                f"| {trade.get('date', trade.get('datetime', ''))} "
                f"| {trade.get('side', '').upper()} "
                f"| {trade.get('symbol', symbol)} "
                f"| {fmt_float(trade.get('price', trade.get('fill_price')), 2)} "
                f"| {trade.get('quantity', trade.get('size', ''))} "
                f"| {pnl:.2f} |"
            )
    else:
        lines.append("*No trade data.*")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by AI Trading Architecture - BacktestReport*")
    return "\n".join(lines)
