"""
WeeklyReviewer — Automated weekly performance review and insight extraction.

Generates comprehensive weekly trading reports including:
- Performance metrics (P&L, win rate, Sharpe, drawdown)
- Best/worst trade analysis
- Strategy comparison
- Reflective sections: "What went well?", "What went poorly?", "What to change?"
- Actionable insights for DSPy prompt optimization

Usage:
    >>> from src.memory import TradeMemory, WeeklyReviewer
    >>> async with TradeMemory() as memory:
    ...     reviewer = WeeklyReviewer(memory)
    ...     report = await reviewer.generate_report()
    ...     reviewer.save_report(report)
    ...     insights = await reviewer.extract_insights()
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from loguru import logger


class WeeklyReviewer:
    """
    Generates weekly trading performance reports and extracts actionable insights.

    Analyzes trade history, identifies patterns, and produces a structured
    report that can be saved for record-keeping and used to optimize DSPy prompts.
    """

    def __init__(
        self,
        trade_memory: Any,  # TradeMemory instance
        report_dir: str = "docs/weekly_reviews",
    ) -> None:
        """
        Initialize the weekly reviewer.

        Args:
            trade_memory: TradeMemory instance for querying trade data.
            report_dir: Directory to save reports.
        """
        self._memory = trade_memory
        self._report_dir = Path(report_dir)
        self._report_dir.mkdir(parents=True, exist_ok=True)

    # ─── Report Generation ─────────────────────────────────────────────

    async def generate_report(
        self,
        end_date: datetime | None = None,
        lookback_days: int = 7,
    ) -> str:
        """
        Generate a comprehensive weekly trading report.

        The report includes:
        - Summary statistics
        - Best/worst trades
        - Strategy performance comparison
        - Pattern analysis
        - Reflective sections: what went well, what went poorly, what to change

        Args:
            end_date: End of the review period (default: now).
            lookback_days: How many days to look back (default: 7).

        Returns:
            Formatted report string.
        """
        if end_date is None:
            end_date = datetime.now(UTC)
        start_date = end_date - timedelta(days=lookback_days)

        logger.info(
            f"[WeeklyReviewer] Generating report for "
            f"{start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        )

        lines: list[str] = []

        # Header
        lines.append("# 📊 Weekly Trading Review")
        lines.append("")
        lines.append(f"**Period:** {start_date.strftime('%Y-%m-%d')} → {end_date.strftime('%Y-%m-%d')}")
        lines.append(f"**Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Section 1: Performance Summary
        lines.extend(await self._section_performance_summary(start_date, end_date))
        lines.append("")

        # Section 2: Best & Worst Trades
        lines.extend(await self._section_best_worst_trades(start_date, end_date))
        lines.append("")

        # Section 3: Strategy Comparison
        lines.extend(await self._section_strategy_comparison(start_date, end_date))
        lines.append("")

        # Section 4: Pattern Analysis
        lines.extend(await self._section_pattern_analysis())
        lines.append("")

        # Section 5: Reflection
        lines.extend(await self._section_reflection(start_date, end_date))
        lines.append("")

        # Section 6: Action Items
        lines.extend(await self._section_action_items(start_date, end_date))
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by WeeklyReviewer — AI Trading Architecture*")

        report = "\n".join(lines)
        logger.info(f"[WeeklyReviewer] Report generated ({len(lines)} lines)")
        return report

    async def _section_performance_summary(
        self, start_date: datetime, end_date: datetime
    ) -> list[str]:
        """Generate the performance summary section."""
        from .trade_memory import PerformanceSummary

        try:
            summary: PerformanceSummary = await self._memory.get_performance_summary(
                start_date=start_date, end_date=end_date
            )
        except Exception as exc:
            logger.warning(f"Failed to get performance summary: {exc}")
            return ["## 📈 Performance Summary\n\n*No data available for this period.*"]

        emoji = "🟢" if summary.total_pnl >= 0 else "🔴"

        lines = [
            "## 📈 Performance Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| {emoji} **Total P&L** | ${summary.total_pnl:+,.2f} |",
            f"| 📊 **Win Rate** | {summary.win_rate:.1f}% ({summary.winning_trades}W / {summary.losing_trades}L) |",
            f"| 📈 **Sharpe Ratio** | {summary.sharpe_ratio:.3f} |",
            f"| 📉 **Max Drawdown** | {summary.max_drawdown:.1f}% |",
            f"| 💰 **Avg P&L/Trade** | ${summary.avg_pnl:+,.2f} |",
            f"| 🏆 **Best Trade** | ${summary.best_trade:+,.2f} |",
            f"| 💔 **Worst Trade** | ${summary.worst_trade:+,.2f} |",
            f"| ⚖️ **Profit Factor** | {summary.profit_factor:.2f} |",
            f"| 📝 **Total Trades** | {summary.total_trades} |",
            "",
        ]

        # Commentary
        if summary.total_trades == 0:
            lines.append("*No closing trades in this period.*")
        else:
            if summary.win_rate >= 60:
                lines.append("✅ Win rate is strong (>60%).")
            elif summary.win_rate >= 45:
                lines.append("⚠️ Win rate is moderate. Consider refining entry signals.")
            else:
                lines.append("🔴 Win rate is below 45%. Significant strategy review needed.")

            if summary.sharpe_ratio >= 1.5:
                lines.append("✅ Risk-adjusted returns are excellent (Sharpe > 1.5).")
            elif summary.sharpe_ratio >= 1.0:
                lines.append("⚠️ Risk-adjusted returns are decent (Sharpe > 1.0).")
            else:
                lines.append("🔴 Risk-adjusted returns need improvement (Sharpe < 1.0).")

        return lines

    async def _section_best_worst_trades(
        self, start_date: datetime, end_date: datetime
    ) -> list[str]:
        """Generate best and worst trades section."""
        try:
            history = await self._memory.get_trade_history(
                start_date=start_date, end_date=end_date, limit=500
            )
        except Exception as exc:
            logger.warning(f"Failed to get trade history: {exc}")
            return ["## 🏆 Best & Worst Trades\n\n*No trade data available.*"]

        if not history:
            return ["## 🏆 Best & Worst Trades\n\n*No trades in this period.*"]

        # Find SELL trades with PnL
        pnl_trades = [t for t in history if t.get("side") == "SELL" and t.get("pnl", 0) != 0]

        if not pnl_trades:
            return ["## 🏆 Best & Worst Trades\n\n*No closing trades with realized P&L.*"]

        best = max(pnl_trades, key=lambda t: t.get("pnl", 0))
        worst = min(pnl_trades, key=lambda t: t.get("pnl", 0))

        lines = [
            "## 🏆 Best & Worst Trades",
            "",
            "### Best Trade",
            "",
            f"- **Symbol:** {best.get('symbol', 'N/A')}",
            f"- **Side:** {best.get('side', 'N/A')} {best.get('quantity', 0)} @ ${best.get('price', 0):,.2f}",
            f"- **P&L:** 🟢 ${best.get('pnl', 0):+.2f} ({best.get('pnl_pct', 0):+.1f}%)",
            f"- **Strategy:** {best.get('strategy', 'N/A')}",
            f"- **AI Confidence:** {best.get('ai_confidence', 'N/A')}",
            "",
            "### Worst Trade",
            "",
            f"- **Symbol:** {worst.get('symbol', 'N/A')}",
            f"- **Side:** {worst.get('side', 'N/A')} {worst.get('quantity', 0)} @ ${worst.get('price', 0):,.2f}",
            f"- **P&L:** 🔴 ${worst.get('pnl', 0):+.2f} ({worst.get('pnl_pct', 0):+.1f}%)",
            f"- **Strategy:** {worst.get('strategy', 'N/A')}",
            f"- **AI Confidence:** {worst.get('ai_confidence', 'N/A')}",
            "",
        ]

        # Add analysis
        best_conf = best.get("ai_confidence")
        worst_conf = worst.get("ai_confidence")

        if best_conf and worst_conf:
            if best_conf > worst_conf:
                lines.append("📌 AI confidence aligned with outcomes (high confidence on wins).")
            else:
                lines.append("⚠️ AI confidence was HIGHER on the losing trade than the winning trade. Review confidence calibration.")

        return lines

    async def _section_strategy_comparison(
        self, start_date: datetime, end_date: datetime
    ) -> list[str]:
        """Generate strategy comparison section."""
        try:
            strat_perf = await self._memory.get_strategy_performance(
                start_date=start_date, end_date=end_date
            )
        except Exception as exc:
            logger.warning(f"Failed to get strategy performance: {exc}")
            return ["## ⚔️ Strategy Comparison\n\n*No strategy data available.*"]

        if not strat_perf:
            return ["## ⚔️ Strategy Comparison\n\n*No strategies with closing trades in this period.*"]

        lines = [
            "## ⚔️ Strategy Comparison",
            "",
        ]

        # Sort by total P&L
        sorted_strats = sorted(
            strat_perf.items(),
            key=lambda x: x[1].total_pnl,
            reverse=True,
        )

        lines.append("| Strategy | Trades | Win Rate | Total P&L | Avg P&L | Sharpe |")
        lines.append("|----------|--------|----------|-----------|---------|--------|")

        for name, perf in sorted_strats:
            emoji = "🟢" if perf.total_pnl >= 0 else "🔴"
            lines.append(
                f"| {emoji} {name} "
                f"| {perf.total_trades} "
                f"| {perf.win_rate:.1f}% "
                f"| ${perf.total_pnl:+,.2f} "
                f"| ${perf.avg_pnl:+,.2f} "
                f"| {perf.sharpe_ratio:.2f} |"
            )

        lines.append("")

        # Winner commentary
        if sorted_strats:
            winner_name, winner_perf = sorted_strats[0]
            lines.append(
                f"🏆 **{winner_name}** was the top-performing strategy "
                f"this week with ${winner_perf.total_pnl:+,.2f} P&L."
            )
            lines.append("")

        return lines

    async def _section_pattern_analysis(self) -> list[str]:
        """Generate pattern analysis section."""
        try:
            patterns = await self._memory.get_trade_patterns()
        except Exception as exc:
            logger.warning(f"Failed to get patterns: {exc}")
            return ["## 🔍 Pattern Analysis\n\n*Unable to analyze patterns.*"]

        lines = [
            "## 🔍 Pattern Analysis",
            "",
        ]

        # Symbol + Side patterns
        sp = patterns.get("symbol_side_patterns", [])
        if sp:
            lines.append("### Symbol + Side Performance")
            lines.append("")
            for p in sp:
                emoji = "🟢" if p["win_rate"] >= 55 else "🔴" if p["win_rate"] < 40 else "⚠️"
                lines.append(
                    f"- {emoji} **{p['symbol']} {p['side']}**: "
                    f"{p['win_rate']}% win rate ({p['total_trades']} trades), "
                    f"avg P&L ${p['avg_pnl']:+,.2f}"
                )
            lines.append("")

        # Time of day patterns
        tp = patterns.get("time_of_day_patterns", [])
        if tp:
            lines.append("### Time-of-Day Patterns (UTC)")
            lines.append("")
            for p in sorted(tp, key=lambda x: x["avg_pnl"], reverse=True)[:5]:
                emoji = "🟢" if p["avg_pnl"] > 0 else "🔴"
                lines.append(
                    f"- {emoji} **{p['hour_utc']:02d}:00 UTC**: "
                    f"{p['win_rate']}% win rate, avg P&L ${p['avg_pnl']:+,.2f}"
                )
            lines.append("")

        # Confidence correlation
        cc = patterns.get("confidence_correlation", {})
        if cc:
            lines.append("### AI Confidence Correlation")
            lines.append("")
            lines.append(
                f"- High confidence (≥70%) avg P&L: ${cc.get('high_confidence_avg_pnl', 0):+.2f} "
                f"({cc.get('high_confidence_count', 0)} trades)"
            )
            lines.append(
                f"- Low confidence (<70%) avg P&L: ${cc.get('low_confidence_avg_pnl', 0):+.2f} "
                f"({cc.get('low_confidence_count', 0)} trades)"
            )
            lines.append("")

        return lines

    async def _section_reflection(
        self, start_date: datetime, end_date: datetime
    ) -> list[str]:
        """Generate the reflective analysis section."""
        try:
            summary = await self._memory.get_performance_summary(
                start_date=start_date, end_date=end_date
            )
            patterns = await self._memory.get_trade_patterns()
        except Exception as exc:
            logger.warning(f"Failed to get reflection data: {exc}")
            return ["## 🤔 Reflection\n\n*Insufficient data for reflection.*"]

        lines = [
            "## 🤔 Reflection",
            "",
        ]

        # What went well
        lines.append("### ✅ What Went Well?")
        lines.append("")

        if summary.total_trades > 0:
            if summary.win_rate >= 55:
                lines.append(
                    f"- Overall win rate of {summary.win_rate:.1f}% is solid. "
                    f"The trading approach is working."
                )

            if summary.profit_factor > 1.5:
                lines.append(
                    f"- Profit factor of {summary.profit_factor:.2f} means "
                    f"we're making more on winners than losing on losers."
                )

            if summary.best_trade > 0:
                lines.append(
                    f"- Best trade earned ${summary.best_trade:+,.2f}. "
                    f"The strategy can capture meaningful moves."
                )

            # Check positive patterns
            good_patterns = [
                p for p in patterns.get("symbol_side_patterns", [])
                if p["win_rate"] >= 60 and p["total_trades"] >= 5
            ]
            if good_patterns:
                symbols = ", ".join(f"{p['symbol']} {p['side']}" for p in good_patterns)
                lines.append(
                    f"- High-win-rate patterns detected: {symbols}. "
                    f"These setups should be prioritized."
                )
        else:
            lines.append("- No completed trades to evaluate. Focus on getting more execution data.")

        lines.append("")

        # What went poorly
        lines.append("### ❌ What Went Poorly?")
        lines.append("")

        if summary.total_trades > 0:
            if summary.win_rate < 45:
                lines.append(
                    f"- Win rate of {summary.win_rate:.1f}% is concerning. "
                    f"Entry signals need refinement."
                )

            if summary.max_drawdown > 10:
                lines.append(
                    f"- Max drawdown of {summary.max_drawdown:.1f}% is significant. "
                    f"Consider tighter stop-losses or smaller position sizes."
                )

            if summary.sharpe_ratio < 0.5:
                lines.append(
                    f"- Sharpe ratio of {summary.sharpe_ratio:.2f} is poor. "
                    f"Risk-adjusted returns need improvement."
                )

            # Bad patterns
            bad_patterns = [
                p for p in patterns.get("symbol_side_patterns", [])
                if p["win_rate"] < 35 and p["total_trades"] >= 5
            ]
            if bad_patterns:
                symbols = ", ".join(f"{p['symbol']} {p['side']}" for p in bad_patterns)
                lines.append(
                    f"- Low-win-rate patterns: {symbols}. "
                    f"These setups should be avoided or reworked."
                )

            # Confidence mismatch
            cc = patterns.get("confidence_correlation", {})
            if cc and cc.get("high_confidence_avg_pnl", 0) < cc.get("low_confidence_avg_pnl", 0):
                lines.append(
                    "- AI confidence is INVERSELY correlated with outcomes. "
                    "High confidence trades performed WORSE than low confidence ones. "
                    "This suggests the AI is overconfident on bad setups."
                )
        else:
            lines.append("- No trades yet to evaluate losses. This is the primary gap.")

        lines.append("")

        # What to change
        lines.append("### 🔄 What to Change?")
        lines.append("")

        if summary.total_trades > 0:
            changes_made = False

            if summary.win_rate < 50:
                lines.append(
                    "- **Raise entry threshold:** Require higher AI confidence "
                    "(≥70%) or stricter technical conditions before entering trades."
                )
                changes_made = True

            if summary.max_drawdown > 8:
                lines.append(
                    "- **Tighten risk limits:** Reduce max position size or "
                    "implement trailing stops to limit drawdowns."
                )
                changes_made = True

            cc = patterns.get("confidence_correlation", {})
            if cc and cc.get("high_confidence_avg_pnl", 0) < 0:
                lines.append(
                    "- **Calibrate AI confidence:** The AI is overconfident on "
                    "losing trades. DSPy optimization should focus on better "
                    "confidence calibration."
                )
                changes_made = True

            if not changes_made:
                lines.append(
                    "- Performance is generally acceptable. Focus on incremental "
                    "improvements rather than major changes."
                )
        else:
            lines.append(
                "- No data-driven changes yet. Focus on executing more trades "
                "to build a statistical foundation."
            )

        lines.append("")

        return lines

    async def _section_action_items(
        self, start_date: datetime, end_date: datetime
    ) -> list[str]:
        """Generate action items section."""
        try:
            summary = await self._memory.get_performance_summary(
                start_date=start_date, end_date=end_date
            )
        except Exception:
            return ["## 📋 Action Items\n\n*Insufficient data for action items.*"]

        lines = [
            "## 📋 Action Items",
            "",
        ]

        priority = 1

        if summary.total_trades == 0:
            lines.append(
                f"{priority}. **Priority:** Get more trade data. "
                "No meaningful analysis possible without completed trades."
            )
            return lines

        if summary.win_rate < 45:
            lines.append(
                f"{priority}. **Priority: HIGH** — Win rate below 45%. "
                f"Review entry signals and consider adding confirmation filters."
            )
            priority += 1

        if summary.max_drawdown > 10:
            lines.append(
                f"{priority}. **Priority: HIGH** — Max drawdown {summary.max_drawdown:.1f}%. "
                "Reduce position sizes or tighten stop-losses."
            )
            priority += 1

        if summary.sharpe_ratio < 1.0 and summary.total_trades > 10:
            lines.append(
                f"{priority}. **Priority: MEDIUM** — Sharpe ratio below 1.0. "
                "DSPy optimization should focus on improving risk-adjusted returns."
            )
            priority += 1

        if summary.profit_factor < 1.2:
            lines.append(
                f"{priority}. **Priority: MEDIUM** — Profit factor below 1.2. "
                "Either cut losers faster or let winners run longer."
            )
            priority += 1

        if priority == 1:
            lines.append(
                "✅ No critical issues detected. Continue current strategy and "
                "monitor for regression."
            )

        lines.append("")

        return lines

    # ─── Report Saving ─────────────────────────────────────────────────

    def save_report(self, report: str, path: str | None = None) -> Path:
        """
        Save a report to the weekly reviews directory.

        Args:
            report: Report content string.
            path: Custom file path. If None, auto-generates filename from date.

        Returns:
            Path to the saved file.
        """
        if path is None:
            date_str = datetime.now(UTC).strftime("%Y-%m-%d")
            filename = f"weekly_review_{date_str}.md"
            filepath = self._report_dir / filename
        else:
            filepath = Path(path)
            filepath.parent.mkdir(parents=True, exist_ok=True)

        filepath.write_text(report, encoding="utf-8")
        logger.info(f"[WeeklyReviewer] Report saved to {filepath}")
        return filepath

    # ─── Insight Extraction ────────────────────────────────────────────

    async def extract_insights(
        self,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
    ) -> list[str]:
        """
        Extract actionable insights for DSPy prompt optimization.

        Analyzes trade history and patterns to produce specific, actionable
        recommendations that can be used to improve AI trading prompts.

        Args:
            start_date: Start of analysis period.
            end_date: End of analysis period.

        Returns:
            List of insight strings, each actionable for prompt tuning.
        """
        if end_date is None:
            end_date = datetime.now(UTC)
        if start_date is None:
            start_date = end_date - timedelta(days=30)

        insights: list[str] = []

        try:
            summary = await self._memory.get_performance_summary(
                start_date=start_date, end_date=end_date
            )
            patterns = await self._memory.get_trade_patterns()
            history = await self._memory.get_trade_history(
                start_date=start_date, end_date=end_date, limit=1000
            )
        except Exception as exc:
            logger.warning(f"Failed to extract insights: {exc}")
            return ["Insufficient data to extract insights. Need more trade history."]

        # Insight 1: Confidence calibration
        cc = patterns.get("confidence_correlation", {})
        if cc:
            high_avg = cc.get("high_confidence_avg_pnl", 0)
            low_avg = cc.get("low_confidence_avg_pnl", 0)
            if high_avg < low_avg:
                insights.append(
                    "PROMPT FIX: The AI is overconfident on losing trades. "
                    "Add explicit instruction: 'Only assign confidence > 70 when "
                    "multiple technical indicators confirm the signal. Be conservative.'"
                )
            elif high_avg > 0 and low_avg < 0:
                insights.append(
                    "PROMPT FIX: AI confidence is well-calibrated — high confidence "
                    "trades are profitable, low confidence trades are not. "
                    "Consider requiring minimum confidence of 60% for trade execution."
                )

        # Insight 2: Symbol-specific patterns
        sp = patterns.get("symbol_side_patterns", [])
        for p in sp:
            if p["win_rate"] >= 65 and p["total_trades"] >= 5:
                insights.append(
                    f"STRATEGY: {p['symbol']} {p['side']} has a {p['win_rate']}% "
                    f"win rate across {p['total_trades']} trades. "
                    f"Prompt should emphasize this setup as a high-conviction pattern."
                )
            elif p["win_rate"] <= 35 and p["total_trades"] >= 5:
                insights.append(
                    f"STRATEGY: {p['symbol']} {p['side']} has a {p['win_rate']}% "
                    f"win rate across {p['total_trades']} trades. "
                    f"Prompt should explicitly warn against this setup or require "
                    f"additional confirmation."
                )

        # Insight 3: Stop-loss / take-profit analysis
        if history:
            sl_hits = 0
            tp_hits = 0
            total_closed = 0

            for trade in history:
                if trade.get("side") != "SELL":
                    continue
                total_closed += 1

                # Check if debate_result mentions SL or TP trigger
                debate = trade.get("debate_result") or {}
                if isinstance(debate, str):
                    try:
                        debate = json.loads(debate)
                    except json.JSONDecodeError:
                        debate = {}

                pnl = trade.get("pnl", 0)
                sl = trade.get("stop_loss")
                tp = trade.get("take_profit")
                price = trade.get("price", 0)

                if sl and pnl < 0:
                    # Estimate if SL was hit
                    price_change = abs(pnl) / (price * trade.get("quantity", 1)) if price > 0 else 0
                    sl_distance = abs(price - sl) / price if price > 0 else 0
                    if price_change >= sl_distance * 0.9:
                        sl_hits += 1

                if tp and pnl > 0:
                    price_change = pnl / (price * trade.get("quantity", 1)) if price > 0 else 0
                    tp_distance = abs(tp - price) / price if price > 0 else 0
                    if price_change >= tp_distance * 0.9:
                        tp_hits += 1

            if total_closed > 0:
                sl_rate = sl_hits / total_closed * 100
                tp_rate = tp_hits / total_closed * 100

                if sl_rate > 60:
                    insights.append(
                        f"RISK: Stop-losses are being hit {sl_rate:.0f}% of the time. "
                        "Prompt should instruct the AI to set wider stop-losses or "
                        "be more selective about entry timing."
                    )
                elif tp_rate > 60:
                    insights.append(
                        f"REWARD: Take-profits are being hit {tp_rate:.0f}% of the time. "
                        "The AI's profit targets are well-calibrated."
                    )
                elif tp_rate < 20 and sl_rate < 20:
                    insights.append(
                        "EXIT STRATEGY: Neither SL nor TP are being hit frequently. "
                        "The AI may be setting unrealistic targets. Prompt should "
                        "instruct to use ATR-based stop-loss and take-profit levels."
                    )

        # Insight 4: Time-of-day optimization
        tp = patterns.get("time_of_day_patterns", [])
        if tp:
            best_hours = sorted(tp, key=lambda x: x["avg_pnl"], reverse=True)[:3]
            worst_hours = sorted(tp, key=lambda x: x["avg_pnl"])[:3]

            if best_hours:
                hours_str = ", ".join(f"{h['hour_utc']:02d}:00" for h in best_hours)
                insights.append(
                    f"TIMING: Best trading hours (UTC): {hours_str}. "
                    "Prompt should note these as high-probability windows."
                )

            if worst_hours:
                hours_str = ", ".join(f"{h['hour_utc']:02d}:00" for h in worst_hours)
                insights.append(
                    f"TIMING: Worst trading hours (UTC): {hours_str}. "
                    "Prompt should add extra caution or require higher confidence "
                    "during these periods."
                )

        # Insight 5: Overall performance directive
        if summary.total_trades >= 10:
            if summary.sharpe_ratio > 1.5:
                insights.append(
                    "OVERALL: Strategy Sharpe ratio is excellent (>1.5). "
                    "DSPy optimization should focus on maintaining current "
                    "performance rather than major changes."
                )
            elif summary.sharpe_ratio > 0:
                insights.append(
                    f"OVERALL: Strategy Sharpe ratio is {summary.sharpe_ratio:.2f}. "
                    f"Focus DSPy optimization on improving risk-adjusted returns. "
                    f"Consider adding risk-reward ratio requirements in prompts."
                )
            else:
                insights.append(
                    f"OVERALL: Strategy Sharpe ratio is {summary.sharpe_ratio:.2f} "
                    f"(negative). Significant prompt redesign needed. "
                    f"Current approach is losing money on average."
                )

        if not insights:
            insights.append(
                "No specific insights available yet. Continue collecting trade data "
                "to enable pattern-based optimization."
            )

        logger.info(f"[WeeklyReviewer] Extracted {len(insights)} insights")
        return insights
