"""
WeeklyReviewer — Automated weekly performance review and insight extraction.

Generates comprehensive weekly trading reports including:
- Performance metrics (P&L, win rate, Sharpe, drawdown)
- Best/worst trade analysis
- Strategy comparison
- Reflective sections: "What went well?", "What went poorly?", "What to change?"
- Actionable insights for DSPy prompt optimization

Usage:
    >>> from src.memory import TradeMemory, WeeklyReviewer
    >>> async with TradeMemory() as memory:
    ...     reviewer = WeeklyReviewer(memory)
    ...     report = await reviewer.generate_report()
    ...     reviewer.save_report(report)
    ...     insights = await reviewer.extract_insights()
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from loguru import logger

from .interfaces import TradeMemoryInterface
from .review.sections import (
    build_action_items_section,
    build_best_worst_trades_section,
    build_pattern_analysis_section,
    build_performance_summary_section,
    build_reflection_section,
    build_strategy_comparison_section,
)


class WeeklyReviewer:
    """
    Generates weekly trading performance reports and extracts actionable insights.

    Analyzes trade history, identifies patterns, and produces a structured
    report that can be saved for record-keeping and used to optimize DSPy prompts.
    """

    def __init__(
        self,
        trade_memory: TradeMemoryInterface,
        report_dir: str = "docs/weekly_reviews",
    ) -> None:
        """
        Initialize the weekly reviewer.

        Args:
            trade_memory: TradeMemoryInterface for querying trade data.
            report_dir: Directory to save reports.
        """
        self._memory = trade_memory
        self._report_dir = Path(report_dir)
        self._report_dir.mkdir(parents=True, exist_ok=True)

    # ─── Report Generation ─────────────────────────────────────────────

    async def generate_report(
        self,
        end_date: datetime | None = None,
        lookback_days: int = 7,
    ) -> str:
        """
        Generate a comprehensive weekly trading report.

        The report includes:
        - Summary statistics
        - Best/worst trades
        - Strategy performance comparison
        - Pattern analysis
        - Reflective sections: what went well, what went poorly, what to change

        Args:
            end_date: End of the review period (default: now).
            lookback_days: How many days to look back (default: 7).

        Returns:
            Formatted report string.
        """
        if end_date is None:
            end_date = datetime.now(timezone.utc)
        start_date = end_date - timedelta(days=lookback_days)

        logger.info(
            f"[WeeklyReviewer] Generating report for "
            f"{start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}"
        )

        lines: list[str] = []

        # Header
        lines.append("# 📊 Weekly Trading Review")
        lines.append("")
        lines.append(f"**Period:** {start_date.strftime('%Y-%m-%d')} → {end_date.strftime('%Y-%m-%d')}")
        lines.append(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Section 1: Performance Summary
        lines.extend(await build_performance_summary_section(self._memory, start_date, end_date))
        lines.append("")

        # Section 2: Best & Worst Trades
        lines.extend(await build_best_worst_trades_section(self._memory, start_date, end_date))
        lines.append("")

        # Section 3: Strategy Comparison
        lines.extend(await build_strategy_comparison_section(self._memory, start_date, end_date))
        lines.append("")

        # Section 4: Pattern Analysis
        lines.extend(await build_pattern_analysis_section(self._memory))
        lines.append("")

        # Section 5: Reflection
        lines.extend(await build_reflection_section(self._memory, start_date, end_date))
        lines.append("")

        # Section 6: Action Items
        lines.extend(await build_action_items_section(self._memory, start_date, end_date))
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by WeeklyReviewer — AI Trading Architecture*")

        report = "\n".join(lines)
        logger.info(f"[WeeklyReviewer] Report generated ({len(lines)} lines)")
        return report


    # ─── Report Saving ─────────────────────────────────────────────────

    def save_report(self, report: str, path: str | None = None) -> Path:
        """
        Save a report to the weekly reviews directory.

        Args:
            report: Report content string.
            path: Custom file path. If None, auto-generates filename from date.

        Returns:
            Path to the saved file.
        """
        if path is None:
            date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            filename = f"weekly_review_{date_str}.md"
            filepath = self._report_dir / filename
        else:
            filepath = Path(path)
            filepath.parent.mkdir(parents=True, exist_ok=True)

        filepath.write_text(report, encoding="utf-8")
        logger.info(f"[WeeklyReviewer] Report saved to {filepath}")
        return filepath

    # ─── Insight Extraction ────────────────────────────────────────────

    async def extract_insights(
        self,
        start_date: datetime | None = None,
        end_date: datetime | None = None,
    ) -> list[str]:
        """
        Extract actionable insights for DSPy prompt optimization.

        Analyzes trade history and patterns to produce specific, actionable
        recommendations that can be used to improve AI trading prompts.

        Args:
            start_date: Start of analysis period.
            end_date: End of analysis period.

        Returns:
            List of insight strings, each actionable for prompt tuning.
        """
        if end_date is None:
            end_date = datetime.now(timezone.utc)
        if start_date is None:
            start_date = end_date - timedelta(days=30)

        insights: list[str] = []

        try:
            summary = await self._memory.get_performance_summary(
                start_date=start_date, end_date=end_date
            )
            patterns = await self._memory.get_trade_patterns()
            history = await self._memory.get_trade_history(
                start_date=start_date, end_date=end_date, limit=1000
            )
        except Exception as exc:
            logger.warning(f"Failed to extract insights: {exc}")
            return ["Insufficient data to extract insights. Need more trade history."]

        # Insight 1: Confidence calibration
        cc = patterns.get("confidence_correlation", {})
        if cc:
            high_avg = cc.get("high_confidence_avg_pnl", 0)
            low_avg = cc.get("low_confidence_avg_pnl", 0)
            if high_avg < low_avg:
                insights.append(
                    "PROMPT FIX: The AI is overconfident on losing trades. "
                    "Add explicit instruction: 'Only assign confidence > 70 when "
                    "multiple technical indicators confirm the signal. Be conservative.'"
                )
            elif high_avg > 0 and low_avg < 0:
                insights.append(
                    "PROMPT FIX: AI confidence is well-calibrated — high confidence "
                    "trades are profitable, low confidence trades are not. "
                    "Consider requiring minimum confidence of 60% for trade execution."
                )

        # Insight 2: Symbol-specific patterns
        sp = patterns.get("symbol_side_patterns", [])
        for p in sp:
            if p["win_rate"] >= 65 and p["total_trades"] >= 5:
                insights.append(
                    f"STRATEGY: {p['symbol']} {p['side']} has a {p['win_rate']}% "
                    f"win rate across {p['total_trades']} trades. "
                    f"Prompt should emphasize this setup as a high-conviction pattern."
                )
            elif p["win_rate"] <= 35 and p["total_trades"] >= 5:
                insights.append(
                    f"STRATEGY: {p['symbol']} {p['side']} has a {p['win_rate']}% "
                    f"win rate across {p['total_trades']} trades. "
                    f"Prompt should explicitly warn against this setup or require "
                    f"additional confirmation."
                )

        # Insight 3: Stop-loss / take-profit analysis
        if history:
            sl_hits = 0
            tp_hits = 0
            total_closed = 0

            for trade in history:
                if trade.get("side") != "SELL":
                    continue
                total_closed += 1

                # Check if debate_result mentions SL or TP trigger
                debate = trade.get("debate_result") or {}
                if isinstance(debate, str):
                    try:
                        debate = json.loads(debate)
                    except json.JSONDecodeError:
                        debate = {}

                pnl = trade.get("pnl", 0)
                sl = trade.get("stop_loss")
                tp = trade.get("take_profit")
                price = trade.get("price", 0)

                if sl and pnl < 0:
                    # Estimate if SL was hit
                    price_change = abs(pnl) / (price * trade.get("quantity", 1)) if price > 0 else 0
                    sl_distance = abs(price - sl) / price if price > 0 else 0
                    if price_change >= sl_distance * 0.9:
                        sl_hits += 1

                if tp and pnl > 0:
                    price_change = pnl / (price * trade.get("quantity", 1)) if price > 0 else 0
                    tp_distance = abs(tp - price) / price if price > 0 else 0
                    if price_change >= tp_distance * 0.9:
                        tp_hits += 1

            if total_closed > 0:
                sl_rate = sl_hits / total_closed * 100
                tp_rate = tp_hits / total_closed * 100

                if sl_rate > 60:
                    insights.append(
                        f"RISK: Stop-losses are being hit {sl_rate:.0f}% of the time. "
                        "Prompt should instruct the AI to set wider stop-losses or "
                        "be more selective about entry timing."
                    )
                elif tp_rate > 60:
                    insights.append(
                        f"REWARD: Take-profits are being hit {tp_rate:.0f}% of the time. "
                        "The AI's profit targets are well-calibrated."
                    )
                elif tp_rate < 20 and sl_rate < 20:
                    insights.append(
                        "EXIT STRATEGY: Neither SL nor TP are being hit frequently. "
                        "The AI may be setting unrealistic targets. Prompt should "
                        "instruct to use ATR-based stop-loss and take-profit levels."
                    )

        # Insight 4: Time-of-day optimization
        tp = patterns.get("time_of_day_patterns", [])
        if tp:
            best_hours = sorted(tp, key=lambda x: x["avg_pnl"], reverse=True)[:3]
            worst_hours = sorted(tp, key=lambda x: x["avg_pnl"])[:3]

            if best_hours:
                hours_str = ", ".join(f"{h['hour_utc']:02d}:00" for h in best_hours)
                insights.append(
                    f"TIMING: Best trading hours (UTC): {hours_str}. "
                    "Prompt should note these as high-probability windows."
                )

            if worst_hours:
                hours_str = ", ".join(f"{h['hour_utc']:02d}:00" for h in worst_hours)
                insights.append(
                    f"TIMING: Worst trading hours (UTC): {hours_str}. "
                    "Prompt should add extra caution or require higher confidence "
                    "during these periods."
                )

        # Insight 5: Overall performance directive
        if summary.total_trades >= 10:
            if summary.sharpe_ratio > 1.5:
                insights.append(
                    "OVERALL: Strategy Sharpe ratio is excellent (>1.5). "
                    "DSPy optimization should focus on maintaining current "
                    "performance rather than major changes."
                )
            elif summary.sharpe_ratio > 0:
                insights.append(
                    f"OVERALL: Strategy Sharpe ratio is {summary.sharpe_ratio:.2f}. "
                    f"Focus DSPy optimization on improving risk-adjusted returns. "
                    f"Consider adding risk-reward ratio requirements in prompts."
                )
            else:
                insights.append(
                    f"OVERALL: Strategy Sharpe ratio is {summary.sharpe_ratio:.2f} "
                    f"(negative). Significant prompt redesign needed. "
                    f"Current approach is losing money on average."
                )

        if not insights:
            insights.append(
                "No specific insights available yet. Continue collecting trade data "
                "to enable pattern-based optimization."
            )

        logger.info(f"[WeeklyReviewer] Extracted {len(insights)} insights")
        return insights
